# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f449e6fa672f69ff38435505d8998623b92d92888284bedb238f27dcd5763b498da4601b71013d65b19fcb70282522b3f7e11772e36c83badf93c34f6ac045f
  google_maps: <%= ENV["GOOGLE_MAPS"] %>
  google_places: <%= ENV["GOOGLE_PLACES"] %>
  geocoder: <%= ENV["GEOCODER"] %>
test:
  secret_key_base: b17fdfe1a649316edf8975df30647005e30ff90a480908039d130129c0f90cc9eb2edd58e719d41d1bce44f4aff18582e5badd9e8987759ab86e5031b67732d8
  google_maps: <%= ENV["GOOGLE_MAPS"] %>
  google_places: <%= ENV["GOOGLE_PLACES"] %>
  geocoder: <%= ENV["GEOCODER"] %>
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps: <%= ENV["GOOGLE_MAPS"] %>
  google_places: <%= ENV["GOOGLE_PLACES"] %>
  geocoder: <%= ENV["GEOCODER"] %>